# Dev profile config: Local PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/bank_sim_dev
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Redis Config (Development)
spring.data.redis.host=localhost
spring.data.redis.port=6379

# Logging Level
logging.level.com.bankSim=DEBUG
